- import_playbook: inventory.yml

- name: Monitoring
  hosts: all
  gather_facts: no
  become: true
  tasks:
  - name: Wait 300 seconds
    wait_for_connection:
      timeout: 300

  - name: Service beamium
    service:
      name: beamium
      state: '{{ state | default(stopped) }}'
